name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

jobs:
  build_and_deploy_job:
    if: github.event_name == 'workflow_dispatch' || github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false
      - name: 'Create env file'
        run: |
          touch .env
          echo CLIENT_ID="${{ secrets.CLIENT_ID }}" >> .env
          echo GET_CURRENT_DATE_CODE="${{ secrets.GET_CURRENT_DATE_CODE }}" >> .env
          echo GET_APPOINTMENTS_CODE="${{ secrets.GET_APPOINTMENTS_CODE }}" >> .env
          echo BOOK_CODE="${{ secrets.BOOK_CODE }}" >> .env
          echo CANCEL_CODE="${{ secrets.CANCEL_CODE }}" >> .env
          echo ADD_TO_WAITING_LIST_CODE="${{ secrets.ADD_TO_WAITING_LIST_CODE }}" >> .env
          echo GET_USER_WAITING_LIST_CODE="${{ secrets.GET_USER_WAITING_LIST_CODE }}" >> .env
          echo DELETE_USER_FROM_WAITING_LIST_CODE="${{ secrets.DELETE_USER_FROM_WAITING_LIST_CODE }}" >> .env
          echo GET_LEGAL_SERVICES_CODE="${{ secrets.GET_LEGAL_SERVICES_CODE }}" >> .env
          echo UPLOAD_CODE="${{ secrets.UPLOAD_CODE }}" >> .env
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BRAVE_ROCK_034AD2303 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/"
          api_location: ""
          output_location: "dist/progetto_client"

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BRAVE_ROCK_034AD2303 }}
          action: "close"
